ShanePark/dutypark

src/main/resources/static/css/base.css
src/main/resources/templates/duty/duty-edit.html
src/main/resources/templates/duty/duty.html

- multiple line memo supported
- original memo will be show up when edit it
- duty readability improved

memo function improved

---

src/main/resources/static/css/base.css
src/main/resources/templates/duty/duty-edit.html
src/main/resources/templates/layout/header.html

- duty change button UI improved
- memo change UI improved

duty edit UI improved

---

src/main/resources/static/css/base.css
src/main/resources/templates/duty/duty-edit.html
src/main/resources/templates/duty/duty.html
src/main/resources/templates/layout/header.html

responsive web design for mobile

---

src/main/kotlin/com/tistory/shanepark/dutypark/duty/controller/DutyController.kt
src/main/resources/static/css/base.css
src/main/resources/templates/duty/duty-edit.html
src/main/resources/templates/layout/header.html

- removed repeated code
- hided scrollbar which was irritating
- added arrow for edit duty page as well

added arrow for edit page

---

src/main/resources/static/css/base.css
src/main/resources/templates/duty/duty-edit.html
src/main/resources/templates/layout/header.html

input password when move to edit page #10

---

src/main/kotlin/com/tistory/shanepark/dutypark/common/filter/IpAccessFilter.kt
src/test/kotlin/com/tistory/shanepark/dutypark/common/filter/IpAccessFilterTest.kt

because of too many random requests

feat: request not with domain address are ignored

---

build.gradle.kts
src/main/kotlin/com/tistory/shanepark/dutypark/common/slack/aspect/SlackNotificationAspect.kt
src/main/kotlin/com/tistory/shanepark/dutypark/duty/controller/DutyController.kt
src/main/kotlin/com/tistory/shanepark/dutypark/duty/repository/DutyRepository.kt
src/main/kotlin/com/tistory/shanepark/dutypark/duty/repository/DutyTypeRepository.kt
src/main/kotlin/com/tistory/shanepark/dutypark/duty/service/DutyService.kt
src/main/kotlin/com/tistory/shanepark/dutypark/member/domain/entity/Department.kt
src/main/kotlin/com/tistory/shanepark/dutypark/member/repository/MemberRepository.kt
src/main/kotlin/com/tistory/shanepark/dutypark/member/service/MemberService.kt
src/main/resources/application.yml
src/main/resources/psw4j.properties

update latency improved: 600ms -> 100ms

read & update optimization

---

src/main/resources/static/css/base.css
src/main/resources/static/css/mquery.css
src/main/resources/templates/duty/duty-edit.html
src/main/resources/templates/duty/duty.html
src/main/resources/templates/layout/header.html

if there's memo on off day, background color was not properly presented. now it's ok

hotfix: duty edit page off+memo color bug fixed

---

src/main/kotlin/com/tistory/shanepark/dutypark/member/domain/dto/DDayDto.kt
src/main/resources/templates/duty/duty.html
src/main/resources/templates/member/d-day.html

now it's calculated from server

hotfix: dDay calculation was not correct

---

src/main/kotlin/com/tistory/shanepark/dutypark/duty/controller/DutyViewController.kt
src/main/kotlin/com/tistory/shanepark/dutypark/member/controller/DDayController.kt
src/main/kotlin/com/tistory/shanepark/dutypark/security/config/JwtAuthInterceptor.kt
src/main/resources/templates/member/d-day.html
src/test/kotlin/com/tistory/shanepark/dutypark/member/service/DDayServiceTest.kt

- DDay update slack notification
- wait me when rearrange dDay orders
- Dday edit -> better experience

hotfix: DDay UX improvement

---

src/main/kotlin/com/tistory/shanepark/dutypark/member/domain/dto/DDayDto.kt
src/main/resources/templates/duty/duty.html
src/main/resources/templates/member/d-day.html

The day after D-Day should be Day 2 (D+2)

fix: D + days calculate fix

---

build.gradle.kts
src/main/kotlin/com/tistory/shanepark/dutypark/DutyparkApplication.kt
src/main/kotlin/com/tistory/shanepark/dutypark/duty/controller/DutyViewController.kt
src/main/kotlin/com/tistory/shanepark/dutypark/security/config/AuthResolver.kt
src/main/kotlin/com/tistory/shanepark/dutypark/security/config/JwtAuthInterceptor.kt
src/main/kotlin/com/tistory/shanepark/dutypark/security/config/JwtConfig.kt
src/main/kotlin/com/tistory/shanepark/dutypark/security/config/SecurityConfig.kt
src/main/kotlin/com/tistory/shanepark/dutypark/security/controller/AuthController.kt
src/main/kotlin/com/tistory/shanepark/dutypark/security/controller/AuthViewController.kt
src/main/kotlin/com/tistory/shanepark/dutypark/security/domain/dto/LoginMember.kt
src/main/kotlin/com/tistory/shanepark/dutypark/security/domain/entity/RefreshToken.kt
src/main/kotlin/com/tistory/shanepark/dutypark/security/service/AuthService.kt
src/main/kotlin/com/tistory/shanepark/dutypark/security/service/JwtProvider.kt
src/main/resources/application.yml
src/test/kotlin/com/tistory/shanepark/dutypark/common/entity/BaseTimeEntityTest.kt
src/test/kotlin/com/tistory/shanepark/dutypark/security/domain/entity/RefreshTokenTest.kt

refresh token records remote info

---

src/main/kotlin/com/tistory/shanepark/dutypark/DutyparkApplication.kt
src/main/kotlin/com/tistory/shanepark/dutypark/admin/controller/AdminViewController.kt
src/main/kotlin/com/tistory/shanepark/dutypark/security/config/AdminAuthInterceptor.kt
src/main/kotlin/com/tistory/shanepark/dutypark/security/config/DutyparkProperties.kt
src/main/kotlin/com/tistory/shanepark/dutypark/security/config/SecurityConfig.kt
src/main/kotlin/com/tistory/shanepark/dutypark/security/domain/entity/RefreshToken.kt
src/main/kotlin/com/tistory/shanepark/dutypark/security/service/AuthService.kt
src/main/resources/templates/admin/index.html

simple admin page to check Refresh Token info

feat: simple admin page

---

src/main/kotlin/com/tistory/shanepark/dutypark/member/controller/RefreshTokenController.kt
src/main/kotlin/com/tistory/shanepark/dutypark/member/repository/RefreshTokenRepository.kt
src/main/kotlin/com/tistory/shanepark/dutypark/member/service/RefreshTokenService.kt
src/main/kotlin/com/tistory/shanepark/dutypark/security/domain/dto/RefreshTokenDto.kt
src/main/kotlin/com/tistory/shanepark/dutypark/security/handlers/LogoutSuccessHandle.kt
src/main/kotlin/com/tistory/shanepark/dutypark/security/service/AuthService.kt
src/main/resources/static/css/base.css
src/main/resources/templates/member/member.html
src/test/kotlin/com/tistory/shanepark/dutypark/common/entity/BaseTimeEntityTest.kt
src/test/kotlin/com/tistory/shanepark/dutypark/member/service/RefreshTokenServiceTest.kt

feat: my login management

---

src/main/kotlin/com/tistory/shanepark/dutypark/duty/controller/DutyController.kt
src/main/kotlin/com/tistory/shanepark/dutypark/duty/service/DutyService.kt
src/main/resources/static/css/base.css
src/main/resources/templates/duty/duty-edit.html
src/main/resources/templates/duty/duty.html
src/main/resources/templates/layout/include.html
src/test/kotlin/com/tistory/shanepark/dutypark/security/controller/AuthViewControllerTest.kt

- memo pre-line now working on edit as well
- edit page have duty-type labels
- smaller buttons for changing duty-type

chore: edit page memo UX enhanced

---

src/main/resources/static/css/base.css
src/main/resources/templates/duty/duty.html
src/main/resources/templates/layout/include.html

so if select d-Day event, it will show the count on current calendar
close #90

feat: D-day calculator added

---

src/main/kotlin/com/tistory/shanepark/dutypark/department/controller/DepartmentAdminController.kt
src/main/kotlin/com/tistory/shanepark/dutypark/security/service/AuthService.kt
src/main/resources/static/css/base.css
src/main/resources/templates/admin/department/department-detail.html
src/main/resources/templates/duty/duty.html
src/main/resources/templates/layout/include.html

- date compare bug fixed
- 12:00 PM bug fixed
- can update department OFF color
- can assign department manager [null]

Hotfix: small design improvement, UX enhancement, bug fix

---

src/main/resources/static/css/base.css
src/main/resources/templates/duty/duty.html
src/main/resources/templates/layout/include.html

- if DAY have any schedule, its' background become darker
- Color of public day (but not holiday) color is not red anymore

Hotfix: some style enhancement

---

src/main/kotlin/com/tistory/shanepark/dutypark/common/advice/ViewExceptionControllerAdvice.kt
src/main/kotlin/com/tistory/shanepark/dutypark/duty/controller/DutyViewController.kt
src/main/kotlin/com/tistory/shanepark/dutypark/security/controller/AuthController.kt
src/main/resources/templates/member/login.html

There is a temporary solution until the `friend` feature is implemented

feat: only logged-in member can view other's duties.

---

.github/workflows/gradle.yml
src/main/resources/application.yml

assign it as text instead and put in on file path

feat: not include key file in class-path

---

src/main/kotlin/com/tistory/shanepark/dutypark/holiday/service/HolidayService.kt

- Implement ReentrantLock in loadAndSaveHolidaysFromAPI to manage concurrency.
- Ensure thread-safe access to holidayMap to avoid duplicate API calls for the same year.
- Add checks to prevent redundant API requests and database operations if data already exists.

refactor: Add thread-safe synchronization to prevent duplicate holiday

---

src/main/resources/static/css/base.css
src/main/resources/templates/duty/duty.html

- now schedule content shows properly when it has multiple lines
- css side effect fixed

Hotfix: fix css side effect and print schedule content properly

---

src/main/resources/templates/duty/duty.html

- 00:01 - 00:01 should show start time
- also 00:00 - 00:01 should show endtime

fix: schedule at 00:01 not showing start time

---

src/main/kotlin/com/tistory/shanepark/dutypark/department/domain/dto/DepartmentDto.kt
src/main/kotlin/com/tistory/shanepark/dutypark/duty/controller/DutyViewController.kt
src/main/kotlin/com/tistory/shanepark/dutypark/member/controller/FriendController.kt
src/main/kotlin/com/tistory/shanepark/dutypark/member/domain/dto/FriendRequestDto.kt
src/main/kotlin/com/tistory/shanepark/dutypark/member/domain/dto/MemberDto.kt
src/main/kotlin/com/tistory/shanepark/dutypark/member/domain/entity/Member.kt
src/main/kotlin/com/tistory/shanepark/dutypark/member/repository/FriendRelationRepository.kt
src/main/kotlin/com/tistory/shanepark/dutypark/member/repository/FriendRequestRepository.kt
src/main/kotlin/com/tistory/shanepark/dutypark/member/repository/MemberRepository.kt
src/main/kotlin/com/tistory/shanepark/dutypark/member/service/FriendService.kt
src/main/kotlin/com/tistory/shanepark/dutypark/member/service/MemberService.kt
src/main/kotlin/com/tistory/shanepark/dutypark/schedule/controller/ScheduleController.kt
src/main/kotlin/com/tistory/shanepark/dutypark/schedule/domain/dto/ScheduleDto.kt
src/main/kotlin/com/tistory/shanepark/dutypark/schedule/domain/entity/Schedule.kt
src/main/kotlin/com/tistory/shanepark/dutypark/schedule/domain/entity/ScheduleTag.kt
src/main/kotlin/com/tistory/shanepark/dutypark/schedule/repository/ScheduleRepository.kt
src/main/kotlin/com/tistory/shanepark/dutypark/schedule/service/ScheduleService.kt
src/main/resources/db/migration/v2/V2.0.6__schedule_tags.sql
src/main/resources/static/css/base.css
src/main/resources/static/lib/vue.js
src/main/resources/templates/duty/duty.html
src/main/resources/templates/layout/include.html
src/main/resources/templates/member/friends.html
src/test/kotlin/com/tistory/shanepark/dutypark/member/controller/FriendControllerTest.kt
src/test/kotlin/com/tistory/shanepark/dutypark/schedule/service/ScheduleServiceTest.kt
src/test/resources/application.yml

Tag friends on schedule

---

src/main/kotlin/com/tistory/shanepark/dutypark/member/service/FriendService.kt
src/main/kotlin/com/tistory/shanepark/dutypark/schedule/domain/dto/ScheduleDto.kt
src/main/kotlin/com/tistory/shanepark/dutypark/schedule/domain/dto/ScheduleUpdateDto.kt
src/main/kotlin/com/tistory/shanepark/dutypark/schedule/repository/ScheduleRepository.kt
src/main/kotlin/com/tistory/shanepark/dutypark/schedule/service/ScheduleService.kt
src/main/resources/static/css/base.css
src/main/resources/static/css/mquery.css
src/main/resources/templates/duty/duty.html
src/main/resources/templates/layout/include.html
src/test/kotlin/com/tistory/shanepark/dutypark/schedule/controller/ScheduleControllerTest.kt
src/test/kotlin/com/tistory/shanepark/dutypark/schedule/service/ScheduleServiceTest.kt

implement schedule visibility 

---

src/main/resources/static/css/base.css
src/main/resources/templates/layout/include.html

white border was useless when OFF color was white. so, all the borders are black from now on

style: better calendar design

---

src/main/resources/templates/duty/duty.html

it was making people get confused when add schedule

style: remove `close` button on schedule detail modal

---

src/main/kotlin/com/tistory/shanepark/dutypark/schedule/service/ScheduleService.kt
src/main/resources/templates/duty/duty.html
src/test/kotlin/com/tistory/shanepark/dutypark/schedule/service/ScheduleServiceTest.kt

can not rearrange tagged schedules
close #175

fix: schedule position swap bug

---

src/main/kotlin/com/tistory/shanepark/dutypark/duty/controller/DutyTypeController.kt
src/main/kotlin/com/tistory/shanepark/dutypark/duty/domain/entity/DutyType.kt
src/main/kotlin/com/tistory/shanepark/dutypark/duty/service/DutyTypeService.kt
src/main/resources/templates/admin/department/department-detail.html
src/test/kotlin/com/tistory/shanepark/dutypark/duty/service/DutyTypeServiceTest.kt

feat: duty type rearrangement

---

src/main/kotlin/com/tistory/shanepark/dutypark/department/domain/entity/Department.kt

when get the max position not use dutyTypes size anymore but do find the max value

fix: dutyType position bug

---

src/main/resources/templates/duty/duty.html

In case `End date-time` was set automatically, if the user change `Start date-time` end date-time also follows it

fix: schedule end-datetime UX improved

---

src/main/kotlin/com/tistory/shanepark/dutypark/common/slack/advice/ErrorDetectAdvisor.kt
src/main/resources/static/css/base.css
src/main/resources/templates/duty/duty.html
src/main/resources/templates/layout/include.html

detailed changes are on its' commit messages

#hotfix  fix some bugs and enhance ui

---

src/main/resources/static/css/base.css
src/main/resources/templates/duty/duty.html
src/main/resources/templates/layout/include.html

in case of too many pages(20+), it was too wide and design was ugly. so, restrict pages to show

design: restrict page numbers on search result

---

src/main/resources/templates/duty/duty.html

- when click schedule chat icon which has schedule detail,  it will show schedule detail text pop up
- can edit schedule start date on schedule edit mode

feat: schedule detail speech bubble
